inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/NestedGroups:
  Max: 5 # default: 3

RSpec/MultipleExpectations:
  Max: 5

Metrics/MethodLength:
  Max: 20

Naming/MethodParameterName:
  MinNameLength: 1
